# Generated by Django 3.2 on 2023-02-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20230215_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
        migrations.RemoveField(
            model_name='title',
            name='year',
        ),
    ]
